"""Controlled browsing vocabulary; canonical source records remain unchanged."""

BUILDING_LABELS = {
    'FullServiceRestaurant': 'Full Service Restaurant',
    'HighriseApartment': 'Highrise Apartment',
    'Hospital': 'Hospital',
    'LargeHotel': 'Large Hotel',
    'LargeOffice': 'Large Office',
    'ManufacturedHome': 'Manufactured / Mobile Home',
    'MediumOffice': 'Medium Office',
    'MidriseApartment': 'Midrise Apartment',
    'MultiFamily2To4': 'Multifamily, 2–4 Units',
    'MultiFamily5PlusLowRise': 'Multifamily, 5+ Units, Low Rise',
    'Outpatient': 'Outpatient',
    'PrimarySchool': 'Primary School',
    'QuickServiceRestaurant': 'Quick Service Restaurant',
    'RetailStandalone': 'Standalone Retail',
    'RetailStripmall': 'Strip Mall',
    'SecondarySchool': 'Secondary School',
    'SingleFamilyAttached': 'Single-family Attached',
    'SingleFamilyDetached': 'Single-family Detached',
    'SmallHotel': 'Small Hotel',
    'SmallOffice': 'Small Office',
    'SuperMarket': 'Supermarket',
    'Warehouse': 'Warehouse',
}

PROGRAM_LABELS = {
    'anesthesia': 'Anesthesia',
    'apartment_unit': 'Apartment unit',
    'attic': 'Attic',
    'auditorium': 'Auditorium',
    'back_space': 'Back space',
    'bakery': 'Bakery',
    'banquet': 'Banquet',
    'basement': 'Basement',
    'biohazard': 'Biohazard',
    'bulk': 'Bulk storage',
    'cafe': 'Cafe',
    'cafeteria': 'Cafeteria',
    'classroom': 'Classroom',
    'cleanwork': 'Clean work',
    'computerroom': 'Computer room',
    'conference': 'Conference',
    'core_retail': 'Core retail',
    'corridor': 'Corridor',
    'corridor2': 'Corridor 2',
    'corridor4': 'Corridor 4',
    'corridor_topfloor': 'Corridor, top floor',
    'deli': 'Deli',
    'dining': 'Dining',
    'dressingroom': 'Dressing room',
    'drystorage': 'Dry storage',
    'elec_mechroom': 'Electrical / mechanical room',
    'elevatorcore': 'Elevator core',
    'elevatorcore4': 'Elevator core 4',
    'elevatorpumproom': 'Elevator pump room',
    'entry': 'Entry',
    'er_exam': 'ER exam',
    'er_nursestn': 'ER nurse station',
    'er_trauma': 'ER trauma',
    'er_triage': 'ER triage',
    'exam': 'Exam',
    'exercise': 'Exercise',
    'fine': 'Fine material storage',
    'front_retail': 'Front retail',
    'guestlounge': 'Guest lounge',
    'guestroom': 'Guest room',
    'guestroom123occ': 'Guest room 123, occupied',
    'guestroom123vac': 'Guest room 123, vacant',
    'guestroom2': 'Guest room 2',
    'guestroom3': 'Guest room 3',
    'guestroom4': 'Guest room 4',
    'guestroom4occ': 'Guest room 4, occupied',
    'guestroom4vac': 'Guest room 4, vacant',
    'guestroom8': 'Guest room 8',
    'gym': 'Gym',
    'gym_audience': 'Gym audience',
    'hall': 'Hall',
    'hall_infil': 'Hall (infil)',
    'hospitalofficeflr1': 'Hospital office, floor 1',
    'hospitalofficeflr5': 'Hospital office, floor 5',
    'icu_nursestn': 'ICU nurse station',
    'icu_open': 'ICU open',
    'icu_patrm': 'ICU patient room',
    'it_room': 'IT room',
    'janitor': 'Janitor',
    'kitchen': 'Kitchen',
    'lab': 'Lab',
    'laundry': 'Laundry',
    'library': 'Library',
    'lobby': 'Lobby',
    'lockerroom': 'Locker room',
    'lounge': 'Lounge',
    'mechanical': 'Mechanical',
    'medgas': 'Medical gas',
    'meeting': 'Meeting',
    'mri': 'MRI',
    'mri_control': 'MRI control',
    'nursestation': 'Nurse station',
    'nursestn': 'Nurse station',
    'office': 'Office',
    'officelarge_data_center': 'Office data center',
    'officelarge_main_data_center': 'Office main data center',
    'or': 'Operating room (OR)',
    'outpatientfloor2work': 'Outpatient work, floor 2',
    'pacu': 'Post-anesthesia care unit (PACU)',
    'patroom': 'Patient room',
    'physicaltherapy': 'Physical therapy',
    'phystherapy': 'Physical therapy',
    'plenum': 'Plenum',
    'point_of_sale': 'Point of sale',
    'preop': 'Pre-op',
    'procedureroom': 'Procedure room',
    'produce': 'Produce',
    'publicrestroom': 'Public restroom',
    'radiology': 'Radiology',
    'reception': 'Reception',
    'restroom': 'Restroom',
    'retail': 'Retail',
    'retail2': 'Retail 2',
    'sales': 'Sales',
    'soil_work': 'Soil work',
    'stafflounge': 'Staff lounge',
    'stair': 'Stair',
    'stair4': 'Stair 4',
    'storage': 'Storage',
    'storage4front': 'Storage 4, front',
    'storage4rear': 'Storage 4, rear',
    'strip_mall_type_1': 'Strip mall, type 1',
    'strip_mall_type_2': 'Strip mall, type 2',
    'strip_mall_type_3': 'Strip mall, type 3',
    'toilet': 'Toilet',
    'undeveloped': 'Undeveloped',
    'vestibule': 'Vestibule',
    'xray': 'X-ray',
}

# Qualify source variants already grouped under a single canonical program.
# Other numbered/source programs retain distinct PROGRAM_LABELS above.
PROGRAM_VARIANT_LABELS = {
    'apartment': 'Apartment unit',
    'apartment_topfloor_ns': 'Apartment unit, top floor NS',
    'apartment_topfloor_we': 'Apartment unit, top floor WE',
    'wholebuilding_lg_office': 'Office, whole-building rule',
    'wholebuilding_lg_office_basement': 'Office, basement',
    'wholebuilding_lg_office_others': 'Office, other floors',
    'wholebuilding_md_office': 'Office, whole-building rule',
    'wholebuilding_sm_office': 'Office, whole-building rule',
}


def building_label(value):
    """Translate only reviewed codes; unknown future strings remain visible."""
    return BUILDING_LABELS.get(value, value)


def program_label(value):
    return PROGRAM_LABELS.get(value, value)


def program_title(row):
    return PROGRAM_VARIANT_LABELS.get(row.get('variant'), program_label(row['program']))
